#!/bin/bash

usage() {

cat <<USAGE
Usage: patchprr <database name> <patch.sql>
USAGE

exit 1

}


if [ $# -lt 2 -o "x$1" == "x-h" -o "x$1" == "x--help" ]
then
  if [ $# == 1 ]
  then
    mysql -u root -h 192.168.160.18 -e "SELECT * FROM (SELECT * FROM $1.Patches p ORDER BY p.ID DESC LIMIT 20) AS p ORDER BY p.ID"
  fi
  usage
fi


mysql -u root -h 192.168.160.18 $1 < $2

rc=$?

if [ "$rc" -eq 0 ]
then
  mysql -u root -h 192.168.160.18 -e "INSERT INTO $1.Patches (Name, CreateTimestamp) VALUES ('$2', NOW())"
  echo Patch applied succesfully
fi
mysql -u root -h 192.168.160.18 -e "SELECT * FROM (SELECT * FROM $1.Patches p ORDER BY p.ID DESC LIMIT 20) AS p ORDER BY p.ID"

